---

- hosts: webservers
  vars:
    - repo_url: https://github.com/git-developers/claro-pool.git
    - app_name: claropool
    - repo_remote: origin
    - repo_version: master
    - webapps_dir: /var/www/html
    - virtualenv_root: /deployed/PleaseDeployMe/mac
    - welcomeMsg: "Pollo gordo 33333333333"

  tasks:
    - name: Git Pull Project
      git: repo={{repo_url}} dest={{webapps_dir}}/{{app_name}} version={{repo_version}} force=yes