app_user_index:
    path:  /
    defaults:
        _controller: AppBundle:User:index
    methods: [GET]

app_user_create:
    path:  /create
    defaults:
        _controller: AppBundle:User:create
    methods: [POST]

app_user_edit:
    path:  /edit
    defaults:
        _controller: AppBundle:User:edit
    requirements:
    methods: [POST, PUT]

app_user_delete:
    path:  /delete
    defaults:
        _controller: AppBundle:User:delete
    requirements:
    methods: [DELETE]

app_user_view:
    path:  /view
    defaults:
        _controller: AppBundle:User:view
    requirements:
    methods: [POST]

app_user_info:
    path:  /info
    defaults:
        _controller: AppBundle:User:info
    requirements:
    methods: [POST]

app_user_search:
    path: /search
    defaults: { _controller: AppBundle:User:search }
    requirements:
    methods: [POST]

app_user_change_password:
    path: /change-password
    defaults: { _controller: AppBundle:User:changePassword }
    requirements:
    methods: [POST, PUT]

app_user_edit_user:
    path: /edit-user
    defaults: { _controller: AppBundle:User:editUser }
    requirements:
    methods: [POST, GET]