services:

    app.listener.doctrine:
        class: AppBundle\EventListener\DoctrineListenerService
        arguments: ["@service_container", "@security.token_storage"]
        tags:
          - { name: doctrine.event_listener, event: postUpdate }
          - { name: doctrine.event_listener, event: preUpdate }
          - { name: doctrine.event_listener, event: prePersist }
          - { name: doctrine.event_listener, event: postLoad }
          - { name: doctrine.event_listener, event: postRemove }

    twig.extension.common:
         class: AppBundle\Twig\Extension\CommonExtension
         arguments: ['@doctrine.orm.entity_manager']
         public: false
         tags:
             - { name: twig.extension }

    app.form.usertype:
        class: AppBundle\Form\UserType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: app.form.usertype }

    app.form.route.type:
        class: AppBundle\Form\RouteType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: app.form.route.type, alias: app.form.route.type }

    app.form.route.conductor.type:
        class: AppBundle\Form\RouteConductorType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: app.form.route.conductor.type, alias: app.form.route.conductor.type }

    app.form.updateprofile.type:
        class: AppBundle\Form\UpdateProfileType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.updateprofile.type, alias: form.updateprofile.type }

    app.form.profiletype:
        class: AppBundle\Form\ProfileType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: core.form.profiletype }

    app.form.producttype:
        class: AppBundle\Form\ProductType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: core.form.producttype }

    app.form.categorytype:
        class: AppBundle\Form\CategoryType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: app.form.categorytype }

    app.form.pointofsaletype:
        class: AppBundle\Form\PointOfSaleType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: app.form.pointofsaletype }

    app.form.reservatype:
        class: AppBundle\Form\ReservaType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: app.form.reservatype }

    twig.extension.boxmapper:
         class: AppBundle\Twig\Extension\BoxMapperExtension
         public: false
         tags:
             - { name: twig.extension }

    #SERVICES
    app.service.cruduser:
        class: AppBundle\Services\CrudUser\CrudUser
        tags:
            - { name: app.service.cruduser, alias: app.service.cruduser }

    app.service.crud:
        class: AppBundle\Services\Crud\Crud
        tags:
            - { name: app.service.crud, alias: app.service.crud }

    app.service.tree:
        class: AppBundle\Services\Tree\Tree
        tags:
            - { name: app.service.tree, alias: app.service.tree }

    app.service.treetoassign:
        class: AppBundle\Services\TreeToAssign\TreeToAssign
        tags:
            - { name: app.service.treetoassign, alias: app.service.treetoassign }
    #SERVICES